//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IDEA.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Badanie_Maszyny
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Badanie_Maszyny()
        {
            this.Badany_Parametr = new HashSet<Badany_Parametr>();
        }
    
        public int ID_Badanie { get; set; }
        public int ID_Maszyny { get; set; }
        public int ID_Pracownicy { get; set; }
        public System.DateTime Data { get; set; }
        public string Opis { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Badany_Parametr> Badany_Parametr { get; set; }
        public virtual Maszyny Maszyny { get; set; }
        public virtual Pracownicy Pracownicy { get; set; }
    }
}
