//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IDEA.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Badany_Parametr
    {
        public int ID_Badany_Parametr { get; set; }
        public int ID_Badanie { get; set; }
        public int ID_Parametr_Maszyny { get; set; }
        public double Wartosc { get; set; }
    
        public virtual Badanie_Maszyny Badanie_Maszyny { get; set; }
        public virtual Parametr_Maszyny Parametr_Maszyny { get; set; }
    }
}
