//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IDEA.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Brakujacy_material
    {
        public string Nazwa_Procesu { get; set; }
        public string Nazwa_Materialu { get; set; }
        public int Ilość_potrzebnego { get; set; }
        public int Ilość_materiału { get; set; }
        public string Jednostka { get; set; }
    }
}
