//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IDEA.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Czas_Pracy_Maszyny_Obslugi
    {
        public int ID_Maszyny { get; set; }
        public string Symbol_maszyny { get; set; }
        public double Przebieg_poczatkowy { get; set; }
        public Nullable<int> Przebie_maszyny_z_procesow { get; set; }
        public double Przebieg_calkowity { get; set; }
        public Nullable<int> ID_Rodzaj_Obslugi_Maszyny { get; set; }
        public string Obsluga_maszyny { get; set; }
        public Nullable<System.DateTime> Data_zakonczenia_obslugi { get; set; }
    }
}
