//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IDEA.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dokumentacja_Pracownicy
    {
        public int ID_Dokumentacja { get; set; }
        public int ID_Pracownicy { get; set; }
        public int ID_Funkcja_w_Dokumentacji { get; set; }
    
        public virtual Dokumentacja Dokumentacja { get; set; }
        public virtual Funkcja_w_Dokumentacji Funkcja_w_Dokumentacji { get; set; }
        public virtual Pracownicy Pracownicy { get; set; }
    }
}
