//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IDEA.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dokumentacja
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Dokumentacja()
        {
            this.Dokumentacja_Pracownicy = new HashSet<Dokumentacja_Pracownicy>();
        }
    
        public int ID_Dokumentacja { get; set; }
        public int ID_Rodzaj_Dokumentacja { get; set; }
        public int ID_Produkt { get; set; }
        public string Plik { get; set; }
        public System.DateTime Data_ { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Dokumentacja_Pracownicy> Dokumentacja_Pracownicy { get; set; }
        public virtual Produkt Produkt { get; set; }
        public virtual Rodzaj_Dokumentacja Rodzaj_Dokumentacja { get; set; }
    }
}
