//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IDEA.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dostawa
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Dostawa()
        {
            this.SkladDostawa_Material = new HashSet<SkladDostawa_Material>();
        }
    
        public int ID_Dostawa { get; set; }
        public int ID_Dostawcy { get; set; }
        public int ID_Pracownik { get; set; }
        public int ID_Magazyn { get; set; }
        public System.DateTime Data { get; set; }
    
        public virtual Dostawcy Dostawcy { get; set; }
        public virtual Magazyn Magazyn { get; set; }
        public virtual Pracownicy Pracownicy { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SkladDostawa_Material> SkladDostawa_Material { get; set; }
    }
}
