//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IDEA.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dostepne_Pojazdy
    {
        public int ID_Pojazd { get; set; }
        public string Marka { get; set; }
        public string Model { get; set; }
        public Nullable<System.DateTime> DataRozchodu { get; set; }
        public System.DateTime Data_Ubezpieczenia { get; set; }
        public System.DateTime Data_przeglądu { get; set; }
    }
}
