//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IDEA.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dostepnosc_Maszyn
    {
        public string Rodzaj_Maszyny { get; set; }
        public string Model_Maszyny { get; set; }
        public string Symbol_Maszyny { get; set; }
        public Nullable<System.DateTime> Data_dostępności { get; set; }
    }
}
