//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IDEA.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dostawy_All
    {
        public int ID_Dostawa { get; set; }
        public string Rodzaj_dostawcy { get; set; }
        public string Nazwa_firmy { get; set; }
        public string Telefon { get; set; }
        public System.DateTime Data { get; set; }
    }
}
