//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IDEA.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Faktury
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Faktury()
        {
            this.Koszty_Rozne = new HashSet<Koszty_Rozne>();
            this.ObslugiPojazdows = new HashSet<ObslugiPojazdow>();
            this.Oplaty_Administracyjne = new HashSet<Oplaty_Administracyjne>();
            this.PrzegladPojazdus = new HashSet<PrzegladPojazdu>();
            this.SkladDostawa_Material = new HashSet<SkladDostawa_Material>();
            this.Srodki_Majatkowe = new HashSet<Srodki_Majatkowe>();
            this.Srodki_Majatkowe1 = new HashSet<Srodki_Majatkowe>();
            this.Tankowanies = new HashSet<Tankowanie>();
            this.Ubezpieczenies = new HashSet<Ubezpieczenie>();
            this.Zamowienia_Klienci = new HashSet<Zamowienia_Klienci>();
        }
    
        public int ID_Faktury { get; set; }
        public int ID_Rodzaj_Faktury { get; set; }
        public System.DateTime Data_Wplywu { get; set; }
        public int Termin_platnosci { get; set; }
        public int ID_Pracownicy { get; set; }
        public string Nazwa_Podmiotu { get; set; }
        public string NIP { get; set; }
        public string Adres_Ulica { get; set; }
        public string Adres_Kod_Pocztowy { get; set; }
        public string Adres_Miasto { get; set; }
        public decimal Kwota_Netto { get; set; }
        public decimal Kwota_Brutto { get; set; }
        public Nullable<System.DateTime> Data_Zaplaty { get; set; }
        public byte[] Plik { get; set; }
        public int ID_Stan_Faktury { get; set; }
    
        public virtual Pracownicy Pracownicy { get; set; }
        public virtual Rodzaj_Faktury Rodzaj_Faktury { get; set; }
        public virtual Stan_Faktury Stan_Faktury { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Koszty_Rozne> Koszty_Rozne { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ObslugiPojazdow> ObslugiPojazdows { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Oplaty_Administracyjne> Oplaty_Administracyjne { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PrzegladPojazdu> PrzegladPojazdus { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SkladDostawa_Material> SkladDostawa_Material { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Srodki_Majatkowe> Srodki_Majatkowe { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Srodki_Majatkowe> Srodki_Majatkowe1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tankowanie> Tankowanies { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ubezpieczenie> Ubezpieczenies { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Zamowienia_Klienci> Zamowienia_Klienci { get; set; }
    }
}
