//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IDEA.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kontrola_Jakosci_Zamowienia
    {
        public int ID_Kontrola_Jakosci_Zamowienia { get; set; }
        public int ID_Sklad_Zamowienia { get; set; }
        public int Zaakcpetowane { get; set; }
        public int Odrzucone { get; set; }
        public System.DateTime Data { get; set; }
        public string Uwagi { get; set; }
    
        public virtual Klient Klient { get; set; }
    }
}
