//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IDEA.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Koszty_Rozne
    {
        public int ID_Koszty_Rozne { get; set; }
        public int ID_Rodzaj_Koszty_Rozne { get; set; }
        public int ID_Pracownicy { get; set; }
        public decimal Kwota_Netto { get; set; }
        public decimal Kwota_Brutto { get; set; }
        public Nullable<int> ID_Faktury { get; set; }
        public System.DateTime Data { get; set; }
    
        public virtual Faktury Faktury { get; set; }
        public virtual Pracownicy Pracownicy { get; set; }
        public virtual Rodzaj_Koszty_Rozne Rodzaj_Koszty_Rozne { get; set; }
    }
}
