//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IDEA.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kosztorys_Roboczogodziny
    {
        public int ID_Zamowienia_Klienci { get; set; }
        public int ID_Sklad_Zamowienia { get; set; }
        public int ID_Produkt { get; set; }
        public Nullable<double> Wartosc_jednostkowa { get; set; }
        public int Ilosc { get; set; }
        public Nullable<double> Wartosc_calkowita { get; set; }
    }
}
