//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IDEA.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kosztory
    {
        public int ID_Sklad_Zamowienia { get; set; }
        public Nullable<double> Wartosc_Calkowita_roboczogodziny { get; set; }
        public Nullable<decimal> Wartosc_calkowita_material { get; set; }
        public int Zlozonosc_produktu { get; set; }
        public Nullable<double> Cena { get; set; }
    }
}
