//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IDEA.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Logistyka_Transport_wewnetrzny
    {
        public int ID_TransportWewnetrzny { get; set; }
        public int ID_Zlecenie_Magazynowe { get; set; }
        public string Magazyn_poczatkowy { get; set; }
        public string Magazyn_docelowy { get; set; }
        public System.DateTime Data_realizacji { get; set; }
        public string Pracownik { get; set; }
        public string Pojazd { get; set; }
    }
}
