//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IDEA.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Maszyny_Ewidencja
    {
        public int ID_Maszyny { get; set; }
        public string Rodzaj_maszyny { get; set; }
        public string Symbol_maszyny { get; set; }
        public string Marka_maszyny { get; set; }
        public string Model_maszyny { get; set; }
        public System.DateTime Data_przychodu { get; set; }
        public Nullable<System.DateTime> Data_rozchodu { get; set; }
        public string Rodzaj_strategii_eksploatacji { get; set; }
    }
}
