//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IDEA.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Material_Wlasciwosc_Material
    {
        public int ID_Material_Wlasciwosc_Material { get; set; }
        public int ID_Material { get; set; }
        public int ID_Wlasciwosc_Materialu { get; set; }
        public double Wartosc { get; set; }
    
        public virtual Material Material { get; set; }
        public virtual Wlasciwosc_Materialu Wlasciwosc_Materialu { get; set; }
    }
}
