//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IDEA.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Material
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Material()
        {
            this.Material_Wlasciwosc_Material = new HashSet<Material_Wlasciwosc_Material>();
            this.Proces_Technologiczny_Material = new HashSet<Proces_Technologiczny_Material>();
            this.RozlozeniePolki_Materialy = new HashSet<RozlozeniePolki_Materialy>();
            this.Sklad_TransportWewnetrzny_Material = new HashSet<Sklad_TransportWewnetrzny_Material>();
            this.Sklad_Zlecenie_Magazynowe = new HashSet<Sklad_Zlecenie_Magazynowe>();
            this.SkladDostawa_Material = new HashSet<SkladDostawa_Material>();
        }
    
        public int ID_Material { get; set; }
        public int ID_Rodzaj_Materialu { get; set; }
        public int ID_Jednostka_miary { get; set; }
        public string Nazwa { get; set; }
        public Nullable<double> Szerokosc { get; set; }
        public Nullable<double> Glebokosc { get; set; }
        public Nullable<double> Wysokosc { get; set; }
        public Nullable<double> Masa { get; set; }
        public string Opis { get; set; }
    
        public virtual Jednostka_miary Jednostka_miary { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Material_Wlasciwosc_Material> Material_Wlasciwosc_Material { get; set; }
        public virtual Rodzaj_Materialu Rodzaj_Materialu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Proces_Technologiczny_Material> Proces_Technologiczny_Material { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RozlozeniePolki_Materialy> RozlozeniePolki_Materialy { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Sklad_TransportWewnetrzny_Material> Sklad_TransportWewnetrzny_Material { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Sklad_Zlecenie_Magazynowe> Sklad_Zlecenie_Magazynowe { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SkladDostawa_Material> SkladDostawa_Material { get; set; }
    }
}
