//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IDEA.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Model_Maszyny
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Model_Maszyny()
        {
            this.Maszynies = new HashSet<Maszyny>();
            this.Normy_Eksploatacyjne = new HashSet<Normy_Eksploatacyjne>();
            this.Parametr_Maszyny = new HashSet<Parametr_Maszyny>();
        }
    
        public int ID_Model_Maszyny { get; set; }
        public int ID_Rodzaj_Strategii_Eksp { get; set; }
        public string Marka { get; set; }
        public string Model { get; set; }
        public int ID_Rodzaj_Maszyny { get; set; }
        public double Koszt_Roboczogodziny { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Maszyny> Maszynies { get; set; }
        public virtual Rodzaj_Strategii_Eksp Rodzaj_Strategii_Eksp { get; set; }
        public virtual Rodzaj_Maszyny Rodzaj_Maszyny { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Normy_Eksploatacyjne> Normy_Eksploatacyjne { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Parametr_Maszyny> Parametr_Maszyny { get; set; }
    }
}
