//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IDEA.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class ModelMaszyny_Parametry
    {
        public string Model_maszyny { get; set; }
        public string Rodzaj_strategii_eksploatacji { get; set; }
        public string Nazwa_Badanrgo_parametru { get; set; }
        public double Nominalna_wartosc_parametru { get; set; }
        public double Minimalna_wartosc_parametru { get; set; }
        public double Maksymalna_wartosc_parametru { get; set; }
    }
}
