//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IDEA.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Narzedzia_w_procesie
    {
        public string Nazwa_Narzedzia { get; set; }
        public string Nazwa_Procesu { get; set; }
        public Nullable<System.DateTime> Data_Rzeczywistego_Rozpoczecia { get; set; }
        public Nullable<System.DateTime> Data_Rzeczywistego_Zakonczenia { get; set; }
    }
}
