//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IDEA.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Narzedzia
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Narzedzia()
        {
            this.Proces_Narzedzia = new HashSet<Proces_Narzedzia>();
        }
    
        public int ID_Narzedzia { get; set; }
        public int ID_Rodzaj_Narzedzia { get; set; }
        public string Symbol { get; set; }
        public string Opis { get; set; }
        public System.DateTime Data_przychodu { get; set; }
        public Nullable<System.DateTime> Data_rozchodu { get; set; }
    
        public virtual Rodzaj_Narzedzia Rodzaj_Narzedzia { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Proces_Narzedzia> Proces_Narzedzia { get; set; }
    }
}
