//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IDEA.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Obslugi
    {
        public int ID_Obslugi { get; set; }
        public int ID_Maszyny { get; set; }
        public int ID_Pracownicy { get; set; }
        public int ID_Rodzaj_Obslugi_Maszyny { get; set; }
        public double Koszt_netto { get; set; }
        public double Koszt_brutto { get; set; }
        public string Opis { get; set; }
        public System.DateTime Data_od { get; set; }
        public System.DateTime Data_do { get; set; }
    
        public virtual Maszyny Maszyny { get; set; }
        public virtual Pracownicy Pracownicy { get; set; }
        public virtual Rodzaj_Obslugi_Maszyny Rodzaj_Obslugi_Maszyny { get; set; }
    }
}
