//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IDEA.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class ObslugiPojazdow
    {
        public int ID_ObslugiPojazdow { get; set; }
        public int ID_Pojazd { get; set; }
        public int ID_RodzajObslugi_Pojazdow { get; set; }
        public int ID_Pracownik { get; set; }
        public System.DateTime Data { get; set; }
        public decimal KosztNetto { get; set; }
        public decimal KosztBrutto { get; set; }
        public Nullable<int> ID_Faktury { get; set; }
    
        public virtual Faktury Faktury { get; set; }
        public virtual Pojazd Pojazd { get; set; }
        public virtual Pracownicy Pracownicy { get; set; }
        public virtual RodzajObslugi_Pojazdow RodzajObslugi_Pojazdow { get; set; }
    }
}
