//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IDEA.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Oplaty_Administracyjne
    {
        public int ID_Oplaty_Administracyjne { get; set; }
        public int ID_Pracownicy { get; set; }
        public int ID_Rodzaj_Oplaty_Administracyjnej { get; set; }
        public string Nazwa { get; set; }
        public decimal Kwota_Netto { get; set; }
        public decimal Kwota_Brutto { get; set; }
        public Nullable<int> ID_Faktury { get; set; }
        public System.DateTime Data { get; set; }
        public Nullable<System.DateTime> Okres_od { get; set; }
        public Nullable<System.DateTime> Okres_do { get; set; }
    
        public virtual Faktury Faktury { get; set; }
        public virtual Pracownicy Pracownicy { get; set; }
        public virtual Rodzaj_Oplaty_Administracyjnej Rodzaj_Oplaty_Administracyjnej { get; set; }
    }
}
