//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IDEA.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Parametr_Maszyny
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Parametr_Maszyny()
        {
            this.Badany_Parametr = new HashSet<Badany_Parametr>();
        }
    
        public int ID_Parametr_Maszyny { get; set; }
        public int ID_Model_Maszyny { get; set; }
        public string Nazwa_Parametru { get; set; }
        public double Wartosc_Nominalna { get; set; }
        public double Dolna_Granica { get; set; }
        public double Gorna_Granica { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Badany_Parametr> Badany_Parametr { get; set; }
        public virtual Model_Maszyny Model_Maszyny { get; set; }
    }
}
