//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IDEA.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pojazdy_All
    {
        public int ID_Pojazd { get; set; }
        public string Marka { get; set; }
        public string Model { get; set; }
        public double PojemnoscSilnika { get; set; }
        public double Nosnosc { get; set; }
        public int Stan_licznika_początkowy { get; set; }
        public string Numer_rejestracyjny { get; set; }
        public System.DateTime Rok_produkcji { get; set; }
        public System.DateTime Data_przychodu { get; set; }
        public Nullable<System.DateTime> Data_rozchodu { get; set; }
        public System.DateTime Data_Ubezpieczenia { get; set; }
        public System.DateTime Data_przeglądu { get; set; }
    }
}
