//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IDEA.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Polka
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Polka()
        {
            this.RozlozeniePolki_Materialy = new HashSet<RozlozeniePolki_Materialy>();
            this.RozlozeniePolki_Produkty = new HashSet<RozlozeniePolki_Produkty>();
        }
    
        public int ID_Polka { get; set; }
        public int ID_Sekcja { get; set; }
        public string Numer { get; set; }
        public double Szerokosc { get; set; }
        public double Glebokosc { get; set; }
        public double Wysokosc { get; set; }
        public double Udzwig { get; set; }
    
        public virtual Sekcja Sekcja { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RozlozeniePolki_Materialy> RozlozeniePolki_Materialy { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RozlozeniePolki_Produkty> RozlozeniePolki_Produkty { get; set; }
    }
}
