//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IDEA.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pracownicy_Stanowisko
    {
        public int ID_Pracownicy_Stanowisko { get; set; }
        public int ID_Pracownicy { get; set; }
        public int ID_Stanowisko { get; set; }
        public System.DateTime Data { get; set; }
    
        public virtual Pracownicy Pracownicy { get; set; }
        public virtual Stanowisko Stanowisko { get; set; }
    }
}
