//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IDEA.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Praca_Pracownikow_Produkcji
    {
        public string Imie { get; set; }
        public string Nazwisko { get; set; }
        public string Nazwa_Stanowiska { get; set; }
        public string Numer_Zamówienia { get; set; }
        public string Nazwa_Procesu { get; set; }
        public int Ilosc_w_procesie { get; set; }
        public System.DateTime Planowana_Data_Zakończenia { get; set; }
        public Nullable<System.DateTime> Rzeczywista_Data_Zakończenia { get; set; }
        public int Czas_pracy_Pracownika__h_ { get; set; }
        public Nullable<int> Czas_pracy_Maszyny__h_ { get; set; }
    }
}
