//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IDEA.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pracownicy_Ewidencja
    {
        public string Imie { get; set; }
        public string Nazwisko { get; set; }
        public string PESEL { get; set; }
        public string Adres_Ulica { get; set; }
        public string Adres_Kod_Pocztowy { get; set; }
        public string Adres_Miasto { get; set; }
        public string Dzial { get; set; }
        public string Stanowisko { get; set; }
        public string Rodzaj_umowy { get; set; }
        public decimal Pensja_Brutto { get; set; }
    }
}
