//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IDEA.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Proces_Technologiczny
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Proces_Technologiczny()
        {
            this.Proces_Technologiczny_Material = new HashSet<Proces_Technologiczny_Material>();
        }
    
        public int ID_Proces_Technologiczny { get; set; }
        public int ID_Produkt { get; set; }
        public int ID_Rodzaj_Maszyny { get; set; }
        public int ID_Nazwa_Procesu { get; set; }
        public int Kolejnosc { get; set; }
        public int Ilosc_Godzin { get; set; }
        public int Ilosc_Pracownikow { get; set; }
    
        public virtual Nazwa_Procesu Nazwa_Procesu { get; set; }
        public virtual Produkt Produkt { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Proces_Technologiczny_Material> Proces_Technologiczny_Material { get; set; }
        public virtual Rodzaj_Maszyny Rodzaj_Maszyny { get; set; }
    }
}
