//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IDEA.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Proces_Technologiczny_Produktu
    {
        public string Nazwa_produktu { get; set; }
        public string Nazwa_Procesu { get; set; }
        public int Kolejnosc { get; set; }
        public string Potrzebny_rodzaj_maszyny { get; set; }
        public int Ilosc_Godzin { get; set; }
        public int Ilosc_Pracownikow { get; set; }
    }
}
