//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IDEA.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Proces
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Proces()
        {
            this.Proces_Narzedzia = new HashSet<Proces_Narzedzia>();
            this.Proces_Pracownicy = new HashSet<Proces_Pracownicy>();
        }
    
        public int ID_Proces { get; set; }
        public int ID_Sklad_Zamowienia { get; set; }
        public int ID_Maszyny { get; set; }
        public int ID_Nazwa_Procesu { get; set; }
        public System.DateTime Data_Planowanego_Rozpoczecia { get; set; }
        public System.DateTime Data_Planowanego_Zakonczenia { get; set; }
        public Nullable<System.DateTime> Data_Rzeczywistego_Rozpoczecia { get; set; }
        public Nullable<System.DateTime> Data_Rzeczywistego_Zakonczenia { get; set; }
        public Nullable<int> Czas_Pracy_Maszyny { get; set; }
    
        public virtual Maszyny Maszyny { get; set; }
        public virtual Nazwa_Procesu Nazwa_Procesu { get; set; }
        public virtual Sklad_Zamowienia Sklad_Zamowienia { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Proces_Narzedzia> Proces_Narzedzia { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Proces_Pracownicy> Proces_Pracownicy { get; set; }
    }
}
