//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IDEA.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Proces_Pracownicy
    {
        public int Proces_Pracownicy1 { get; set; }
        public int ID_Proces { get; set; }
        public int ID_Pracownicy { get; set; }
        public int Czas_Pracy { get; set; }
    
        public virtual Pracownicy Pracownicy { get; set; }
        public virtual Proce Proce { get; set; }
    }
}
