//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IDEA.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Produkt
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Produkt()
        {
            this.Dokumentacjas = new HashSet<Dokumentacja>();
            this.Nierozlozone_Produkty = new HashSet<Nierozlozone_Produkty>();
            this.Proces_Technologiczny = new HashSet<Proces_Technologiczny>();
            this.RozlozeniePolki_Produkty = new HashSet<RozlozeniePolki_Produkty>();
            this.Sklad_Zamowienia = new HashSet<Sklad_Zamowienia>();
            this.Sklad_Zlecenie_Produkt = new HashSet<Sklad_Zlecenie_Produkt>();
            this.SkladWysylka_Produkt = new HashSet<SkladWysylka_Produkt>();
        }
    
        public int ID_Produkt { get; set; }
        public int ID_Rodzaj_Produktu { get; set; }
        public string Nazwa { get; set; }
        public double Szerokosc { get; set; }
        public double Glebokosc { get; set; }
        public double Wysokosc { get; set; }
        public double Masa { get; set; }
        public int Zlozonosc_produktu { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Dokumentacja> Dokumentacjas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Nierozlozone_Produkty> Nierozlozone_Produkty { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Proces_Technologiczny> Proces_Technologiczny { get; set; }
        public virtual Rodzaj_Produktu Rodzaj_Produktu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RozlozeniePolki_Produkty> RozlozeniePolki_Produkty { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Sklad_Zamowienia> Sklad_Zamowienia { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Sklad_Zlecenie_Produkt> Sklad_Zlecenie_Produkt { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SkladWysylka_Produkt> SkladWysylka_Produkt { get; set; }
    }
}
