//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IDEA.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Produkty_Procesy
    {
        public int ID_Produkt { get; set; }
        public string Produkt { get; set; }
        public string Nazwa_procesu { get; set; }
        public double Koszt_Roboczogodziny { get; set; }
    }
}
