//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IDEA.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Przeglady_View
    {
        public int ID_PrzegladPojazdu { get; set; }
        public string Pojazd { get; set; }
        public string Numer_rejestracyjny { get; set; }
        public Nullable<System.DateTime> Data_przegladu { get; set; }
        public Nullable<System.DateTime> Data_waznosci_ { get; set; }
        public int KosztBrutto { get; set; }
        public int KosztNetto { get; set; }
    }
}
