//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IDEA.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Raport_z_pracy_Operatorow
    {
        public string Imie { get; set; }
        public string Nazwisko { get; set; }
        public string Nazwa_Stanowiska { get; set; }
        public Nullable<int> Czas_pracy__h_ { get; set; }
    }
}
