//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IDEA.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class RodzajObsl_Model
    {
        public string Nazwa { get; set; }
        public string Symbol { get; set; }
        public System.DateTime Data_od { get; set; }
        public System.DateTime Data_do { get; set; }
        public double Koszt_brutto { get; set; }
    }
}
