//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IDEA.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class RozlozeniePolki_Materialy
    {
        public int ID_RozlozeniePolki_Materialy { get; set; }
        public int ID_Polka { get; set; }
        public int ID_Material { get; set; }
        public int ID_Pracownik { get; set; }
        public int Ilosc { get; set; }
        public System.DateTime Data { get; set; }
        public bool CzyPobrane { get; set; }
    
        public virtual Material Material { get; set; }
        public virtual Polka Polka { get; set; }
        public virtual Pracownicy Pracownicy { get; set; }
    }
}
