//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IDEA.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class SkladWysylka_Produkt
    {
        public int ID_SkladWysylka_Produkt { get; set; }
        public int ID_Wysylka { get; set; }
        public int ID_Pojazd { get; set; }
        public int ID_Produkt { get; set; }
        public int ID_Pracownik { get; set; }
        public int Ilosc { get; set; }
    
        public virtual Pojazd Pojazd { get; set; }
        public virtual Pracownicy Pracownicy { get; set; }
        public virtual Produkt Produkt { get; set; }
        public virtual Wysylka Wysylka { get; set; }
    }
}
