//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IDEA.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sklad_Zamowienia
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Sklad_Zamowienia()
        {
            this.Zlecenie_Magazynowe = new HashSet<Zlecenie_Magazynowe>();
            this.Proces = new HashSet<Proce>();
        }
    
        public int ID_Sklad_Zamowienia { get; set; }
        public int ID_Zamowienia_Klienci { get; set; }
        public int ID_Produkt { get; set; }
        public int Ilosc { get; set; }
        public decimal Cena_Netto { get; set; }
        public decimal Cena_Brutto { get; set; }
        public string Komentarz { get; set; }
    
        public virtual Klient Klient { get; set; }
        public virtual Produkt Produkt { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Zlecenie_Magazynowe> Zlecenie_Magazynowe { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Proce> Proces { get; set; }
    }
}
