//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IDEA.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sklad_Zlecenie_Magazynowe
    {
        public int ID_Sklad_Zlecenie_Magazynowe { get; set; }
        public int ID_Zlecenie_Magazynowe { get; set; }
        public int ID_Material { get; set; }
        public System.DateTime Data { get; set; }
        public string CzyZlecenieStale { get; set; }
        public string Zwrot { get; set; }
        public string Uwagi { get; set; }
    
        public virtual Material Material { get; set; }
        public virtual Zlecenie_Magazynowe Zlecenie_Magazynowe { get; set; }
    }
}
