//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IDEA.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class SprawdzeniePowierzchniRoboczej
    {
        public string Nazwa { get; set; }
        public int PowierzchniaRobocza { get; set; }
        public Nullable<double> SumaPowierzchniRoboczych { get; set; }
    }
}
