//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IDEA.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Srodki_Majatkowe
    {
        public int ID_Srodki_Majatkowe { get; set; }
        public string Nazwa { get; set; }
        public string Symbol { get; set; }
        public int ID_Dzialy { get; set; }
        public decimal Koszt_Zakupu_Netto { get; set; }
        public decimal Koszt_Zakupu_Brutto { get; set; }
        public Nullable<int> ID_Faktury_Zakup { get; set; }
        public System.DateTime Data_Przychodu { get; set; }
        public Nullable<decimal> Przychod_Ze_Sprzedazy_Netto { get; set; }
        public Nullable<decimal> Przychod_Ze_Sprzedazy_Brutto { get; set; }
        public Nullable<int> ID_Faktury_Sprzedaz { get; set; }
        public Nullable<System.DateTime> Data_Rozchodu { get; set; }
    
        public virtual Dzialy Dzialy { get; set; }
        public virtual Faktury Faktury { get; set; }
        public virtual Faktury Faktury1 { get; set; }
    }
}
