//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IDEA.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class StanLicznika
    {
        public int ID_StanLicznika { get; set; }
        public int ID_Pojazd { get; set; }
        public int ID_Pracownik { get; set; }
        public double StanLicznika1 { get; set; }
        public System.DateTime Data { get; set; }
    
        public virtual Pojazd Pojazd { get; set; }
        public virtual Pracownicy Pracownicy { get; set; }
    }
}
