//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IDEA.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transport_wewnetrzny_Material
    {
        public int ID_Zlecenie_Magazynowe { get; set; }
        public string Material { get; set; }
        public System.DateTime Data_Zlecenia { get; set; }
        public int Ilosc_sztuk { get; set; }
        public Nullable<double> Objetosc_zamowienia { get; set; }
        public Nullable<double> Masa_zamowienia { get; set; }
    }
}
