//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IDEA.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ubezpieczenie
    {
        public int ID_Ubezpieczenie { get; set; }
        public int ID_Pojazd { get; set; }
        public int ID_Ubezpieczyciel { get; set; }
        public int ID_RodzajUbezpieczenia { get; set; }
        public Nullable<System.DateTime> DataOd { get; set; }
        public Nullable<System.DateTime> DataDo { get; set; }
        public int KosztNetto { get; set; }
        public int KosztBrutto { get; set; }
        public Nullable<int> ID_Faktury { get; set; }
    
        public virtual Faktury Faktury { get; set; }
        public virtual Pojazd Pojazd { get; set; }
        public virtual RodzajUbezpieczenia RodzajUbezpieczenia { get; set; }
        public virtual Ubezpieczyciel Ubezpieczyciel { get; set; }
    }
}
