//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IDEA.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Urlopy
    {
        public int ID_Urlopy { get; set; }
        public int ID_Pracownicy { get; set; }
        public int ID_Rodzaj_Urlopu { get; set; }
        public System.DateTime Data_od { get; set; }
        public System.DateTime Data_do { get; set; }
        public int Dni_Robocze { get; set; }
    
        public virtual Pracownicy Pracownicy { get; set; }
        public virtual Rodzaj_Urlopu Rodzaj_Urlopu { get; set; }
    }
}
