//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IDEA.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_Faktury
    {
        public int ID_Faktury { get; set; }
        public string Rodzaj_Faktury { get; set; }
        public System.DateTime Data_Wplywu { get; set; }
        public int Termin_platnosci { get; set; }
        public string Pracownik { get; set; }
        public string Nazwa_Podmiotu { get; set; }
        public string NIP { get; set; }
        public string Adres_Ulica { get; set; }
        public string Adres_Kod_Pocztowy { get; set; }
        public string Adres_Miasto { get; set; }
        public decimal Kwota_Netto { get; set; }
        public decimal Kwota_Brutto { get; set; }
        public Nullable<System.DateTime> Data_Zaplaty { get; set; }
        public string Stan_Faktury { get; set; }
    }
}
