//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IDEA.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_Zamowienia_Klienci
    {
        public int ID_Zamowienia { get; set; }
        public string Imie_Klienta { get; set; }
        public string Nazwisko_Klienta { get; set; }
        public string Imie_Pracownika { get; set; }
        public string Nazwisko_Pracownika { get; set; }
        public System.DateTime Data_Zamowienia { get; set; }
        public System.DateTime Data_Realizacji { get; set; }
        public string Numer { get; set; }
        public Nullable<int> ID_Faktury { get; set; }
    }
}
