//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IDEA.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Widok_Model_Stategia_ST
    {
        public string Symbol { get; set; }
        public string Nazwa { get; set; }
        public string Nazwa_Parametru { get; set; }
        public double Dolna_Granica { get; set; }
        public double Gorna_Granica { get; set; }
        public double Wartosc { get; set; }
        public System.DateTime Data { get; set; }
    }
}
