//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IDEA.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Wlasciwosc_Materialu
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Wlasciwosc_Materialu()
        {
            this.Material_Wlasciwosc_Material = new HashSet<Material_Wlasciwosc_Material>();
        }
    
        public int ID_Wlasciwosc_Materialu { get; set; }
        public string Nazwa { get; set; }
        public int ID_Jednostka_miary { get; set; }
    
        public virtual Jednostka_miary Jednostka_miary { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Material_Wlasciwosc_Material> Material_Wlasciwosc_Material { get; set; }
    }
}
