//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IDEA.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Wysylka
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Wysylka()
        {
            this.SkladWysylka_Produkt = new HashSet<SkladWysylka_Produkt>();
            this.ZdarzenieWysylka = new HashSet<ZdarzenieWysylka>();
        }
    
        public int ID_Wysylka { get; set; }
        public int ID_Pracownik { get; set; }
        public int ID_ZamowieniaKlienci { get; set; }
        public int ID_Magazyn { get; set; }
        public double Odleglosc { get; set; }
        public string Adres { get; set; }
        public System.DateTime Data { get; set; }
    
        public virtual Magazyn Magazyn { get; set; }
        public virtual Pracownicy Pracownicy { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SkladWysylka_Produkt> SkladWysylka_Produkt { get; set; }
        public virtual Zamowienia_Klienci Zamowienia_Klienci { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ZdarzenieWysylka> ZdarzenieWysylka { get; set; }
    }
}
