//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IDEA.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Wysylki_All
    {
        public int ID_wysyłki { get; set; }
        public string Pracownik { get; set; }
        public string Klient { get; set; }
        public string Magazyn { get; set; }
        public string Adres { get; set; }
        public double Odległość { get; set; }
        public System.DateTime Data { get; set; }
    }
}
