//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IDEA.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Zamowienia_Klienci
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Zamowienia_Klienci()
        {
            this.Wysylkas = new HashSet<Wysylka>();
            this.ZamowieniaKlienci_StatusZamowienia = new HashSet<ZamowieniaKlienci_StatusZamowienia>();
        }
    
        public int ID_Zamowienia_Klienci { get; set; }
        public int ID_Klient { get; set; }
        public int ID_Pracownicy { get; set; }
        public System.DateTime Data_Zamowienia { get; set; }
        public System.DateTime Data_Realizacji { get; set; }
        public string Numer { get; set; }
        public Nullable<int> ID_Faktury { get; set; }
    
        public virtual Faktury Faktury { get; set; }
        public virtual Klient Klient { get; set; }
        public virtual Pracownicy Pracownicy { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Wysylka> Wysylkas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ZamowieniaKlienci_StatusZamowienia> ZamowieniaKlienci_StatusZamowienia { get; set; }
    }
}
