//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IDEA.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class ZamowieniaKlienci_StatusZamowienia
    {
        public int ID_ZamowieniaKlienci_StatusZamowienia { get; set; }
        public int ID_Zamowienia_Klienci { get; set; }
        public int ID_Status_Zamowienia { get; set; }
        public System.DateTime Data { get; set; }
    
        public virtual Status_Zamowienia Status_Zamowienia { get; set; }
        public virtual Zamowienia_Klienci Zamowienia_Klienci { get; set; }
    }
}
