//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IDEA.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Zblizajaca_obsuga_PP
    {
        public int ID_Maszyny { get; set; }
        public int ID_Model_Maszyny { get; set; }
        public string Symbol_maszyny { get; set; }
        public int ID_Rodzaj_Obslugi_Maszyny { get; set; }
        public string Obsluga_maszyny { get; set; }
    }
}
