//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IDEA.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class ZleceniaStale
    {
        public int ID_ZleceniaStale { get; set; }
        public int ID_Zlecenie_Magazynowe { get; set; }
        public short Co_ile { get; set; }
        public System.DateTime DataDo { get; set; }
    
        public virtual Zlecenie_Magazynowe Zlecenie_Magazynowe { get; set; }
    }
}
