//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IDEA.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Zlecenie_Magazynowe
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Zlecenie_Magazynowe()
        {
            this.Sklad_Zlecenie_Magazynowe = new HashSet<Sklad_Zlecenie_Magazynowe>();
            this.Sklad_Zlecenie_Produkt = new HashSet<Sklad_Zlecenie_Produkt>();
            this.TransportWewnetrznies = new HashSet<TransportWewnetrzny>();
            this.ZleceniaStales = new HashSet<ZleceniaStale>();
        }
    
        public int ID_Zlecenie_Magazynowe { get; set; }
        public Nullable<int> ID_Sklad_Zamowienia { get; set; }
        public Nullable<int> ID_Pracownicy { get; set; }
        public int ID_Magazyn { get; set; }
        public System.DateTime Data { get; set; }
        public string CzyZlecenieStale { get; set; }
        public Nullable<bool> Zwrot { get; set; }
        public string Uwagi { get; set; }
    
        public virtual Magazyn Magazyn { get; set; }
        public virtual Pracownicy Pracownicy { get; set; }
        public virtual Sklad_Zamowienia Sklad_Zamowienia { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Sklad_Zlecenie_Magazynowe> Sklad_Zlecenie_Magazynowe { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Sklad_Zlecenie_Produkt> Sklad_Zlecenie_Produkt { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TransportWewnetrzny> TransportWewnetrznies { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ZleceniaStale> ZleceniaStales { get; set; }
    }
}
