//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IDEA.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class NormyEksploatacyjne_Pojazd
    {
        public int ID_ModelPojazd { get; set; }
        public string JednostkaMiar { get; set; }
        public string RemontSredni { get; set; }
        public string RemontGlowny { get; set; }
    
        public virtual ModelePojazdu ModelePojazdu { get; set; }
    }
}
