//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IDEA.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class ZdarzenieWysylka
    {
        public int ID_ZdarzenieWysylka { get; set; }
        public int ID_Wysylka { get; set; }
        public int ID_RodzajZdarzenia_Wysylka { get; set; }
        public string Opis { get; set; }
    
        public virtual RodzajZdarzenia_Wysylka RodzajZdarzenia_Wysylka { get; set; }
        public virtual Wysylka Wysylka { get; set; }
    }
}
